### ISSUE TITLE
Configuration required for using esm2ut33_650M_UR50D

### ISSUE THREAD

**Issue by moonhuwaa** [dimiboeckaerts/PhageRBPdetection#7]
Hi,
I tried using esm2ut33_650M_UR50D to generate protein sequence embeddings, but when faced with longer sequence lengths (such as 6800), my server experienced memory or graphics memory overflow. Have you ever encountered a similar situation? What is the required server configuration for generating long sequence protein embeddings?
Thanks,
Moonhuwaa.

**Comment by dimiboeckaerts** [comment]
Hi Moonhuwaa. Thanks for trying out PhageRBPdetect! Indeed, very long sequences are difficult/impossible to generate representations for in full, as the memory requirements are just too much. I never explicitly ran some experiments to know what is possible at which memory requirement, but if you have a bigger GPU available (24GB/40GB/80GB), I would advise to run on that, instead of the Colab notebook. A second workaround would be to split the protein in two pieces, compute embeddings for both parts separately and then average them. Also, a relevant question to start with would be: which protein could be _that_ long? Hope you can proceed!
